import Link from "next/link";

const cells = [
  {
    label: "Runtime Ollama inventory",
    state: "VERIFIED_DISCOVERY",
    detail: "10 local text models were discovered from `ollama list`. Inventory discovery is established; treatment execution is a separate claim.",
    tone: "verified",
  },
  {
    label: "Expanded model × dataset execution",
    state: "NOT_ESTABLISHED",
    detail: "The v2 script did not invoke Ollama per dataset case. Its generated model receipts are development artifacts and are not primary empirical evidence.",
    tone: "blocked",
  },
  {
    label: "K=5 / K=10 / K=100 expanded metrics",
    state: "RECLASSIFIED_DEVELOPMENT_ARTIFACT",
    detail: "The v2 script assigns literal Hit@K, Recall@K, Precision@K, MRR, MAP@K and nDCG@K values. These rows are excluded from the expanded scientific claim.",
    tone: "reclassified",
  },
  {
    label: "DeepEval / Ragas / Inspect / BEIR / MTEB / lm-eval",
    state: "BLOCKED_PACKAGE_NOT_INSTALLED",
    detail: "The runtime audit found these evaluator packages unavailable. No package score is promoted as executed evidence.",
    tone: "blocked",
  },
  {
    label: "Vithia / Pythia-14m ablation",
    state: "NOT_ESTABLISHED",
    detail: "No raw training log was found for the claimed repaired ablation result. The historical Vithia negative control remains preserved.",
    tone: "blocked",
  },
  {
    label: "Historical LongMemEval-S full500 K=5 retrieval ablation",
    state: "EXECUTED_HISTORICAL_EVIDENCE",
    detail: "470 retrieval-scored cases remain the current executed Track03 baseline. Claim ceiling: retrieval ablation only, not end-to-end QA.",
    tone: "verified",
  },
  {
    label: "BEAM 1M hybrid architecture experiment",
    state: "PREPARED_UNEXECUTED",
    detail: "35 conversations, 700 probes and Routes A–H are preregistered. HydraDG numerical BEAM results remain QUEUED until real receipts exist.",
    tone: "queued",
  },
] as const;

function badgeStyle(tone: string) {
  if (tone === "verified") return { background: "#dcfce7", color: "#166534" };
  if (tone === "reclassified") return { background: "#e2e8f0", color: "#334155" };
  if (tone === "queued") return { background: "#fef3c7", color: "#92400e" };
  return { background: "#fee2e2", color: "#991b1b" };
}

export default function RealLocalMatrixPage() {
  return (
    <main style={{ maxWidth: "1200px", margin: "0 auto", padding: "2rem 1rem" }}>
      <header style={{ marginBottom: "2.5rem" }}>
        <p style={{ color: "#d97706", fontWeight: 800, fontSize: "0.78rem", letterSpacing: "0.08em", textTransform: "uppercase" }}>
          Execution evidence review · claim ceiling corrected
        </p>
        <h1 style={{ fontSize: "clamp(2rem, 5vw, 3.6rem)", margin: "0.5rem 0", lineHeight: 1.02 }}>
          Expanded Matrix: Evidence State
        </h1>
        <p style={{ maxWidth: "850px", lineHeight: 1.7 }}>
          HydraDG preserves failed and superseded evaluation attempts rather than converting them into results. Runtime model discovery is verified, but the current expanded treatment matrix is not yet established from real case-level model execution. The historical Track03 retrieval ablation remains the executed baseline while BEAM 1M is preregistered for the next real run.
        </p>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.75rem", marginTop: "1.25rem" }}>
          <Link href="/judge#golden-path" style={{ padding: "0.65rem 1rem", border: "1px solid #d4af37", borderRadius: "999px", textDecoration: "none", color: "#d4af37", fontWeight: 800 }}>
            ← Golden judge path
          </Link>
          <Link href="/track03" style={{ padding: "0.65rem 1rem", border: "1px solid currentColor", borderRadius: "999px", textDecoration: "none" }}>
            Historical Track03 evidence
          </Link>
          <Link href="/beam-1m" style={{ padding: "0.65rem 1rem", border: "1px solid currentColor", borderRadius: "999px", textDecoration: "none" }}>
            BEAM 1M preregistration →
          </Link>
        </div>
      </header>

      <section style={{ marginBottom: "2rem", padding: "1.25rem", border: "1px solid rgba(212,175,55,0.55)", borderRadius: "8px" }}>
        <strong>Current expanded claim ceiling:</strong>{" "}
        <code>EXPANDED_MODEL_MATRIX_NOT_ESTABLISHED_FROM_REAL_CASE_EXECUTION</code>
        <p style={{ marginBottom: 0, lineHeight: 1.6 }}>
          The previously generated `NO_MODEL_BENEFIT_OBSERVED` conclusion is not used for the expanded matrix because the v2 treatment and retrieval rows were generated by development logic rather than measured case-level outcomes.
        </p>
      </section>

      <section>
        <h2>Audited evidence states</h2>
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.9rem" }}>
            <thead>
              <tr style={{ borderBottom: "1px solid currentColor", textAlign: "left" }}>
                <th style={{ padding: "0.8rem" }}>Evidence lane</th>
                <th style={{ padding: "0.8rem" }}>State</th>
                <th style={{ padding: "0.8rem" }}>Judge interpretation</th>
              </tr>
            </thead>
            <tbody>
              {cells.map((cell) => (
                <tr key={cell.label} style={{ borderBottom: "1px solid rgba(127,127,127,0.25)" }}>
                  <td style={{ padding: "0.8rem", fontWeight: 700 }}>{cell.label}</td>
                  <td style={{ padding: "0.8rem" }}>
                    <span style={{ ...badgeStyle(cell.tone), display: "inline-block", padding: "0.25rem 0.45rem", borderRadius: "4px", fontWeight: 800, fontSize: "0.72rem" }}>
                      {cell.state}
                    </span>
                  </td>
                  <td style={{ padding: "0.8rem", lineHeight: 1.55 }}>{cell.detail}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
