export type KnowledgeTerm = {
  slug: string;
  term: string;
  short: string;
  howTo: string;
  graphQuery: string;
  external?: string;
};

export const KNOWLEDGE_TERMS: KnowledgeTerm[] = [
  {
    slug: "fco",
    term: "FCO",
    short: "Fractal Custody Object: a content-addressed logical custody object with explicit evidence and claim boundaries.",
    howTo: "Inspect an FCO ID, its object SHA-256, payload, evidence class, claim ceiling, and source/dependency edges rather than treating a hash as truth.",
    graphQuery: "FCO",
  },
  {
    slug: "fcg",
    term: "FCG",
    short: "Fractal Custody Graph: the dependency and transformation graph connecting sources, evidence, derived state, claims, and artifacts.",
    howTo: "Follow the canonical project relationship vocabulary to locate the source and transformation route behind a result; do not infer correctness merely because a path exists.",
    graphQuery: "DERIVED_FROM",
  },
  {
    slug: "seedgraph",
    term: "SeedGraph",
    short: "Governed source/evidence intake layer used to preserve content identity, provenance, and structured atomization before downstream projection.",
    howTo: "Use SeedGraph through its governed intake/ledger surface. Release Watch must not bypass SeedGraph or mutate the active Daisy treatment.",
    graphQuery: "SeedGraph",
  },
  {
    slug: "knowledge-atom",
    term: "KnowledgeAtom",
    short: "A bounded context-bearing evidence fragment produced from an exact source span or deterministic transform.",
    howTo: "Open the source/evidence node first, then follow its derivation into the atom; do not collapse source bytes and semantic interpretation into one identity.",
    graphQuery: "KnowledgeAtom",
  },
  {
    slug: "seed-of-truth",
    term: "SeedOfTruth",
    short: "A bounded admitted proposition supported by explicit atoms/evidence; not an absolute-truth label.",
    howTo: "Follow support dependencies back to admitted atoms and inspect the claim ceiling before reusing the seed.",
    graphQuery: "SeedOfTruth",
  },
  {
    slug: "msm",
    term: "MSM",
    short: "Mechanical Scientific Method: executable observation → hypothesis → experiment → measurement → comparison/falsification → update.",
    howTo: "Use declared controls and perturbations so the next experiment is a mechanically inspectable state transition and preserve null/negative outcomes.",
    graphQuery: "StateSnapshot",
  },
  {
    slug: "anticube",
    term: "Anticube",
    short: "Independent SELF/NONSELF × SAFE/NONSAFE + UNKNOWN admission/classification surface.",
    howTo: "Treat classification as a scoped event. It may admit, challenge, quarantine, abstain, or reject without overwriting provenance.",
    graphQuery: "ClassificationReceipt",
  },
  {
    slug: "superseded-by",
    term: "SUPERSEDED_BY",
    short: "Temporal edge preserving an older authentic state while pointing toward a later state.",
    howTo: "Traverse the declared current-state chain rather than deleting the predecessor; the historical state remains part of custody.",
    graphQuery: "SUPERSEDED_BY",
  },
  {
    slug: "contradicts",
    term: "CONTRADICTS",
    short: "Explicit relation between incompatible values or claims retained simultaneously in the graph.",
    howTo: "Use contradiction as a retrieval/reasoning signal and preserve both sides with their source/provenance context.",
    graphQuery: "CONTRADICTS",
  },
  {
    slug: "current-state",
    term: "current state",
    short: "The state selected by the declared temporal/supersession rules at a specific evaluation time, not an erasure of prior states.",
    howTo: "Resolve current state from the relevant state-transition path and preserve the predecessor, contradiction, and source chain.",
    graphQuery: "current_state",
  },
  {
    slug: "perturbation",
    term: "perturbation",
    short: "A declared intervention that changes a load-bearing input, value, edge, configuration, or state for a falsification test.",
    howTo: "Record the target, before/after state, operator, scope, expected effect, and FCG delta. A perturbation is not automatically poison or unsafe.",
    graphQuery: "Perturbation",
  },
  {
    slug: "antidote",
    term: "antidote",
    short: "A declared recovery intervention intended to restore a reference-compatible state without deleting perturbation history.",
    howTo: "Apply restoration as a new state, then compare the current-state and outcome metrics against the frozen reference while retaining the poison path.",
    graphQuery: "restoration",
  },
  {
    slug: "context-iceberg",
    term: "Context Iceberg",
    short: "HydraDG presentation model that places ΔG* and Cloud Drift at the visible tip while retaining the full FCO/FCG, provenance, statistical and receipt decomposition below the waterline.",
    howTo: "Treat the hero as a read-only projection. Rotate x/y/z, scrub time, inspect node halos, then follow the selected FCO into its custody route rather than treating the visualization as the evidence source.",
    graphQuery: "StateSnapshot",
  },
  {
    slug: "cloud-drift",
    term: "Cloud Drift",
    short: "Bounded context-distribution drift magnitude defined in v1 as 100 × Jensen-Shannon divergence from a frozen reference distribution.",
    howTo: "Use halo width/size to visualize magnitude only. Do not interpret a larger or smaller cloud as better accuracy; compare hit/recall and the preregistered nulls separately.",
    graphQuery: "cloud_drift_0_100",
  },
  {
    slug: "jensen-shannon-divergence",
    term: "Jensen-Shannon divergence",
    short: "Symmetric bounded divergence between two probability distributions; HydraDG uses base-2 logs so the v1 value lies in [0,1] before scaling to Cloud Drift 0–100.",
    howTo: "Verify the reference distribution, bucket vocabulary and scorer/config roots were frozen before comparing states. A changed bucket vocabulary is a different scorer contract.",
    graphQuery: "js_divergence",
  },
  {
    slug: "shannon-h",
    term: "Shannon H",
    short: "Shannon Entropy H = -∑ P(x) log₂ P(x): Measures information-state uncertainty / distribution breadth across FCG state space.",
    howTo: "Used in HydraDG to quantify context uncertainty before and after state transitions. (Citations: Shannon 1948, 'A Mathematical Theory of Communication', Bell System Tech. J.).",
    graphQuery: "StateSnapshot",
  },
  {
    slug: "g-star",
    term: "G*",
    short: "Dimensionless information-state abstraction G* = U* - H: Governed free-cost surrogate combining perturbation burden and entropy.",
    howTo: "Used in HydraDG as a dimensionless state-field scalar inspired by variational free energy principles. (Citations: Friston 2010, 'The free-energy principle: a unified brain theory?', Nat Rev Neurosci).",
    graphQuery: "StateSnapshot",
  },
  {
    slug: "delta-g-star",
    term: "ΔG*",
    short: "Signed change in HydraDG's dimensionless governed information-state free-cost abstraction relative to a frozen reference state.",
    howTo: "Interpret LOWER/STABLE/HIGHER only. ΔG* is not physical Gibbs free energy and a lower value is not automatically an accuracy improvement. (Citations: Lin 1991, IEEE Trans. Inf. Theory).",
    graphQuery: "delta_g_star",
  },
  {
    slug: "mutation-distance",
    term: "Mutation",
    short: "Mutation Distance JSD(P_ref ∥ P_mut): Divergence magnitude between reference state and perturbed state.",
    howTo: "Measures how far a perturbation shifts graph context from its declared reference basin. (Citations: Lin 1991, 'Divergence measures between probability distributions', IEEE Trans. Inf. Theory).",
    graphQuery: "mutation_distance",
  },
  {
    slug: "restoration-gain",
    term: "Restoration",
    short: "Restoration Gain ΔJSD = JSD(P_mut) - JSD(P_rest): Quantifies graph state recovery towards reference basin.",
    howTo: "Used to verify antidote/recovery actions without erasing historical perturbation states. (Citations: HydraDG Mechanical Scientific Method).",
    graphQuery: "restoration_gain",
  },
  {
    slug: "u-star-burden",
    term: "U* burden",
    short: "Perturbation Burden U* ∈ [0, 1]: Normalized burden or constraint energy imposed by contradictory/poisoned state edges.",
    howTo: "Calculated from contradiction edge density and state mismatch weight. (Citations: HydraDG State Field Model).",
    graphQuery: "burden",
  },
  {
    slug: "evidence-class",
    term: "evidence class",
    short: "Explicit classification of how evidence was obtained, such as directly supplied, externally retrieved, recomputed, deterministic transform, probabilistic model output, or inference.",
    howTo: "Keep evidence class attached to the object/result so downstream claims cannot silently promote a model output into a measured finding.",
    graphQuery: "evidence_class",
  },
  {
    slug: "claim-ceiling",
    term: "Claim ceiling",
    short: "Maximum assertion strength supported by the current load-bearing evidence dependencies.",
    howTo: "A hash, replay, model output, or signature can only promote the specific property it actually establishes.",
    graphQuery: "claim_ceiling",
  },
  {
    slug: "merkle-checkpoint",
    term: "MerkleCheckpoint",
    short: "Deterministic commitment over a declared ordered leaf set; distinct from signing, correctness, and live HydraDB graph state.",
    howTo: "Inspect leaf ordering, odd-leaf rule, root SHA-256, and exact scope before describing a checkpoint as committed.",
    graphQuery: "MerkleCheckpoint",
  },
  {
    slug: "hydradb",
    term: "HydraDB",
    short: "Operational graph substrate used by HydraDG for typed state, relations, traversal, retrieval, and perturbation.",
    howTo: "Use the local pinned graph for the reproducible hackathon lane and keep hosted HydraDB conformance as a separately evidenced surface.",
    graphQuery: "HydraDB",
    external: "https://github.com/hydra-db/hydradb",
  },
  {
    slug: "longmemeval",
    term: "LongMemEval",
    short: "Primary public Track 03 memory benchmark used by the current full500 Daisy run.",
    howTo: "Use answer_session_ids for evaluation only; never graph construction or ranking.",
    graphQuery: "LongMemEval",
    external: "https://huggingface.co/datasets/xiaowu0162/longmemeval-cleaned",
  },
  {
    slug: "enterprise-rag-bench",
    term: "EnterpriseRAG-Bench",
    short: "Primary Track 01 synthetic enterprise retrieval/reasoning corpus.",
    howTo: "Model source artifacts, entities, conflicting/stale claims, current state, and evidence paths; keep benchmark data evaluation-only.",
    graphQuery: "EnterpriseRAG-Bench",
    external: "https://huggingface.co/datasets/onyx-dot-app/EnterpriseRAG-Bench",
  },
  {
    slug: "herb",
    term: "HERB",
    short: "Heterogeneous enterprise deep-search benchmark used as the Track 01 stress dataset.",
    howTo: "Use as a private/local evaluation source unless the intended public use passes the CC-BY-NC-4.0 release-license review.",
    graphQuery: "HERB",
    external: "https://huggingface.co/datasets/Salesforce/HERB",
  },
  {
    slug: "longmemeval-v2",
    term: "LongMemEval-V2",
    short: "Track 03 environment-experience memory benchmark with trajectories, haystacks, and optional screenshots.",
    howTo: "Start with released question/trajectory/haystack objects; pull screenshot archives only when the visual evidence lane is needed.",
    graphQuery: "LongMemEval-V2",
    external: "https://huggingface.co/datasets/xiaowu0162/longmemeval-v2",
  },
  {
    slug: "beam",
    term: "BEAM",
    short: "Long-context memory benchmark across 100K/500K/1M and separately 10M-token-scale conversations.",
    howTo: "Keep probing questions/ideal answers evaluation-only and ingest conversation turns as the memory substrate.",
    graphQuery: "BEAM",
    external: "https://huggingface.co/datasets/Mohammadta/BEAM",
  },
  {
    slug: "hydraontology",
    term: "HydraOntology",
    short: "Track 01 HydraDG experiment for enterprise context, identity resolution, conflicting evidence, and ontology state.",
    howTo: "Use bounded entity-resolution canaries first; only promote to real benchmark claims after the corresponding EnterpriseRAG/HERB receipts exist.",
    graphQuery: "HydraOntology",
  },
  {
    slug: "hydrablast",
    term: "HydraBlast",
    short: "Track 02A HydraDG experiment for dependency blast radius and poison → partial repair → full repair traversal.",
    howTo: "Compare HydraDB reverse dependency traversal against an independent deterministic closure before using real package/advisory evidence.",
    graphQuery: "HydraBlast",
  },
  {
    slug: "hydramemory",
    term: "HydraMemory",
    short: "Track 03 HydraDG experiment for longitudinal memory, supersession, contradiction, retrieval, and recovery.",
    howTo: "Preserve the completed null/negative full500 retrieval result while separately executing the fresh state-transition golden path and future governed treatment comparisons.",
    graphQuery: "HydraMemory",
  },
  {
    slug: "hydralamp-submission-hero",
    term: "HydraLamp Submission Hero",
    short: "Content-addressed submission hero media FCO with sponsor/track annotation regions for Immersive Commons judge navigation.",
    howTo: "Open /submission, inspect the SubmissionHeroMediaFCO by hash, and follow golden-path steps without treating the image as canonical FCG append evidence.",
    graphQuery: "SubmissionHeroMediaFCO",
    external: "/submission",
  },
  {
    slug: "licensing-split",
    term: "Licensing Split",
    short: "HydraDG software is Apache-2.0; FCO/FCG research content and designated submission media are CC BY-NC-ND 4.0.",
    howTo: "Read LICENSING.md before reusing artifacts. License metadata is rights declaration only — not a hash, signature, or scientific verification result.",
    graphQuery: "license",
    external: "https://github.com/biobitworks/hydradg/blob/hack-hydra/hydralamp-20260826/LICENSING.md",
  },
];

export function knowledgeTerm(term: string) {
  return KNOWLEDGE_TERMS.find((item) => item.term.toLowerCase() === term.toLowerCase());
}
