export type KnowledgeTerm = {
  slug: string;
  term: string;
  short: string;
  howTo: string;
  graphQuery: string;
  external?: string;
};

export const KNOWLEDGE_TERMS: KnowledgeTerm[] = [
  {
    slug: "fco",
    term: "FCO",
    short: "Fractal Custody Object: a content-addressed logical custody object with explicit evidence and claim boundaries.",
    howTo: "Inspect an FCO ID, its object SHA-256, payload, evidence class, claim ceiling, and source/dependency edges rather than treating a hash as truth.",
    graphQuery: "FCO",
  },
  {
    slug: "fcg",
    term: "FCG",
    short: "Fractal Custody Graph: the dependency and transformation graph connecting sources, evidence, derived state, claims, and artifacts.",
    howTo: "Follow the canonical project relationship vocabulary to locate the source and transformation route behind a result; do not infer correctness merely because a path exists.",
    graphQuery: "DERIVED_FROM",
  },
  {
    slug: "seedgraph",
    term: "SeedGraph",
    short: "Governed source/evidence intake layer used to preserve content identity, provenance, and structured atomization before downstream projection.",
    howTo: "Use SeedGraph through its governed intake/ledger surface. HydraDG may project admitted objects downstream, but Release Watch must not bypass SeedGraph or mutate the active Daisy treatment.",
    graphQuery: "SeedGraph",
  },
  {
    slug: "knowledge-atom",
    term: "KnowledgeAtom",
    short: "A bounded context-bearing evidence fragment produced from an exact source span or deterministic transform.",
    howTo: "Open the source/evidence node first, then follow its derivation into the atom; do not collapse source bytes and semantic interpretation into one identity.",
    graphQuery: "KnowledgeAtom",
  },
  {
    slug: "seed-of-truth",
    term: "SeedOfTruth",
    short: "A bounded admitted proposition supported by explicit atoms/evidence; not an absolute-truth label.",
    howTo: "Follow support dependencies back to admitted atoms and inspect the claim ceiling before reusing the seed.",
    graphQuery: "SeedOfTruth",
  },
  {
    slug: "msm",
    term: "MSM",
    short: "Mechanical Scientific Method: executable observation → hypothesis → experiment → measurement → comparison/falsification → update.",
    howTo: "Use declared controls and perturbations so the next experiment is a mechanically inspectable state transition and preserve null/negative outcomes.",
    graphQuery: "StateSnapshot",
  },
  {
    slug: "anticube",
    term: "Anticube",
    short: "Independent SELF/NONSELF × SAFE/NONSAFE + UNKNOWN admission/classification surface.",
    howTo: "Treat classification as a scoped event. It may admit, challenge, quarantine, abstain, or reject without overwriting provenance.",
    graphQuery: "ClassificationReceipt",
  },
  {
    slug: "superseded-by",
    term: "SUPERSEDED_BY",
    short: "Temporal edge preserving an older authentic state while pointing toward a later state.",
    howTo: "Traverse the declared current-state chain rather than deleting the predecessor; the historical state remains part of custody.",
    graphQuery: "SUPERSEDED_BY",
  },
  {
    slug: "contradicts",
    term: "CONTRADICTS",
    short: "Explicit relation between incompatible values or claims retained simultaneously in the graph.",
    howTo: "Use contradiction as a retrieval/reasoning signal and preserve both sides with their source/provenance context.",
    graphQuery: "CONTRADICTS",
  },
  {
    slug: "current-state",
    term: "current state",
    short: "The state selected by the declared temporal/supersession rules at a specific evaluation time, not an erasure of prior states.",
    howTo: "Resolve current state from the relevant state-transition path and preserve the predecessor, contradiction, and source chain.",
    graphQuery: "current_state",
  },
  {
    slug: "perturbation",
    term: "perturbation",
    short: "A declared intervention that changes a load-bearing input, value, edge, configuration, or state for a falsification test.",
    howTo: "Record the target, before/after state, operator, scope, expected effect, and FCG delta. A perturbation is not automatically poison or unsafe.",
    graphQuery: "Perturbation",
  },
  {
    slug: "antidote",
    term: "antidote",
    short: "A declared recovery intervention intended to restore a reference-compatible state without deleting perturbation history.",
    howTo: "Apply restoration as a new state, then compare the current-state and outcome metrics against the frozen reference while retaining the poison path.",
    graphQuery: "restoration",
  },
  {
    slug: "g-star",
    term: "G*",
    short: "HydraDG's preregistered dimensionless information-system free-cost abstraction; it is not physical Gibbs free energy.",
    howTo: "Read G* only under a frozen scorer/config. Release Watch displays the value but must not choose or change its weights.",
    graphQuery: "g_star",
  },
  {
    slug: "delta-g-star",
    term: "ΔG*",
    short: "Signed change in the HydraDG G* abstraction relative to a frozen reference state.",
    howTo: "Interpret only as LOWER, STABLE, or HIGHER. Do not color a negative ΔG* green or equate it with improved accuracy; outcome metrics are separate.",
    graphQuery: "delta_g_star",
  },
  {
    slug: "context-iceberg",
    term: "Context Iceberg",
    short: "Simple-to-deep visualization: ΔG* and Cloud Drift at the tip, empirical outcomes at the waterline, and full FCO/FCG lineage below water.",
    howTo: "Start at the two headline scores, move the time slider, select a context cloud, then drill into the FCO, neighboring FCG edges, source/version, and claim ceiling.",
    graphQuery: "ContextDriftObservation",
  },
  {
    slug: "context-cloud",
    term: "context cloud",
    short: "A visualization envelope around an atom/FCO/state/subtree that displays declared context-change magnitude and direction over time.",
    howTo: "Cloud width uses CloudDrift only when a canonical object/scope receipt supplies it. Color uses signed ΔG* direction; size may use a separately declared normalized burden. Inherited or demo metrics must be labelled.",
    graphQuery: "context_cloud",
  },
  {
    slug: "cloud-drift",
    term: "Cloud Drift",
    short: "Bounded context redistribution magnitude defined in v1 as 100 × Jensen-Shannon divergence under a frozen bucket vocabulary and reference distribution.",
    howTo: "Freeze the context-cloud vocabulary and reference distribution first. A changed Cloud Drift value is not an accuracy result and is not a custody break by itself.",
    graphQuery: "cloud_drift_0_100",
  },
  {
    slug: "jensen-shannon-divergence",
    term: "Jensen-Shannon divergence",
    short: "Symmetric bounded divergence used by the Context Iceberg v1 to compare current and reference context-cloud distributions.",
    howTo: "Use base-2 logarithms with the same frozen vocabulary for both distributions; HydraDG scales JSD by 100 for the Cloud Drift display.",
    graphQuery: "js_divergence",
  },
  {
    slug: "context-drift-observation",
    term: "ContextDriftObservation",
    short: "Planned canonical custody object binding reference state, current state, scorer/config, drift diagnostics, outcome deltas, nulls, and claim ceiling.",
    howTo: "Do not mint a competing canonical object type. Release Watch may display the projection contract; Daisy/canonical FCO/FCG binding must establish the actual project object and edges.",
    graphQuery: "ContextDriftObservation",
  },
  {
    slug: "total-atomization",
    term: "total atomization",
    short: "Dataset custody requirement separating exact byte coverage from complete logical-record coverage, with zero orphan atoms before FULL structural atomization can be claimed.",
    howTo: "Verify source-byte coverage = 1.0, logical-record coverage = 1.0, orphan count = 0, and exact source-file ancestry before promoting the dataset state.",
    graphQuery: "FULL_STRUCTURAL_ATOMIZATION",
  },
  {
    slug: "evidence-class",
    term: "evidence class",
    short: "Explicit classification of how evidence was obtained, such as directly supplied, externally retrieved, recomputed, deterministic transform, probabilistic model output, or inference.",
    howTo: "Keep evidence class attached to the object/result so downstream claims cannot silently promote a model output into a measured finding.",
    graphQuery: "evidence_class",
  },
  {
    slug: "claim-ceiling",
    term: "claim ceiling",
    short: "Maximum assertion strength supported by the current load-bearing evidence dependencies.",
    howTo: "A hash, replay, model output, signature, or graph path can only promote the specific property it actually establishes.",
    graphQuery: "claim_ceiling",
  },
  {
    slug: "merkle-checkpoint",
    term: "MerkleCheckpoint",
    short: "Deterministic commitment over a declared ordered leaf set; distinct from signing, correctness, and live HydraDB graph state.",
    howTo: "Inspect leaf ordering, odd-leaf rule, root SHA-256, and exact scope before describing a checkpoint as committed.",
    graphQuery: "MerkleCheckpoint",
  },
  {
    slug: "hydradb",
    term: "HydraDB",
    short: "Operational graph substrate used by HydraDG for typed state, relations, traversal, retrieval, and perturbation.",
    howTo: "Use the local pinned graph for the reproducible lane and keep hosted HydraDB conformance as a separately evidenced surface.",
    graphQuery: "HydraDB",
    external: "https://github.com/hydra-db/hydradb",
  },
  {
    slug: "longmemeval",
    term: "LongMemEval",
    short: "Primary public Track 03 memory benchmark used by the completed full500 Daisy retrieval ablation.",
    howTo: "Keep benchmark answer/session labels evaluation-only; they must not enter graph construction or ranking.",
    graphQuery: "LongMemEval",
    external: "https://huggingface.co/datasets/xiaowu0162/longmemeval-cleaned",
  },
  {
    slug: "enterprise-rag-bench",
    term: "EnterpriseRAG-Bench",
    short: "Primary Track 01 enterprise retrieval/reasoning corpus currently downloaded and hash-manifested for a bounded future canary.",
    howTo: "Model source artifacts, entities, conflicting/stale claims, current state, and evidence paths; do not claim Track 01 benchmark performance before an executed receipt exists.",
    graphQuery: "EnterpriseRAG-Bench",
    external: "https://huggingface.co/datasets/onyx-dot-app/EnterpriseRAG-Bench",
  },
  {
    slug: "herb",
    term: "HERB",
    short: "Heterogeneous enterprise benchmark retained as a rights-gated Track 01 stress dataset.",
    howTo: "Keep dataset bytes out of the public release unless the release-rights gate explicitly allows them; metadata and manifests may remain in the registry.",
    graphQuery: "HERB",
    external: "https://huggingface.co/datasets/Salesforce/HERB",
  },
  {
    slug: "longmemeval-v2",
    term: "LongMemEval-V2",
    short: "Downloaded Track 03 extension dataset with trajectories/haystacks and optional visual evidence lanes.",
    howTo: "Keep it separate from the frozen LongMemEval-S experiment until its role, null, adapter, and evaluator are declared.",
    graphQuery: "LongMemEval-V2",
    external: "https://huggingface.co/datasets/xiaowu0162/longmemeval-v2",
  },
  {
    slug: "beam",
    term: "BEAM",
    short: "Downloaded long-context memory benchmark reserved for future adapter/evaluation work; BEAM-10M remains deferred.",
    howTo: "Keep probing questions/ideal answers evaluation-only and admit the dataset through the same source/rights/atomization/FCG/HydraDB gates before evaluation.",
    graphQuery: "BEAM",
    external: "https://huggingface.co/datasets/Mohammadta/BEAM",
  },
  {
    slug: "hydraontology",
    term: "HydraOntology",
    short: "Track 01 HydraDG experiment for enterprise context, identity resolution, conflicting evidence, and ontology state.",
    howTo: "Use bounded entity-resolution canaries first; only promote to real benchmark claims after the corresponding EnterpriseRAG/HERB receipts exist.",
    graphQuery: "HydraOntology",
  },
  {
    slug: "hydrablast",
    term: "HydraBlast",
    short: "Track 02A HydraDG experiment for dependency blast radius and poison → partial repair → full repair traversal.",
    howTo: "Compare HydraDB reverse dependency traversal against an independent deterministic closure before using real package/advisory evidence.",
    graphQuery: "HydraBlast",
  },
  {
    slug: "hydramemory",
    term: "HydraMemory",
    short: "Track 03 HydraDG experiment for longitudinal memory, supersession, contradiction, retrieval, and recovery.",
    howTo: "Preserve the completed null/negative full500 retrieval result while separately executing the fresh state-transition golden path and future governed treatment comparisons.",
    graphQuery: "HydraMemory",
  },
];

export function knowledgeTerm(term: string) {
  return KNOWLEDGE_TERMS.find((item) => item.term.toLowerCase() === term.toLowerCase());
}
